/**
 * Copyright (C) 2020
 * All rights reserved, Designed By AiCoder.
 * date 2021-01-28 14:42:55
 */
export const tableOption = {
    dialogDrag: true,
    border: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    align: 'center',
    menuType: 'text',
    searchShow: false,
    excelBtn: true,
    printBtn: true,
    column: [
    {
            label: '记录编号',
            prop: 'id',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '租户编号',
            prop: 'tenantId',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '日志类型',
            prop: 'type',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '日志标题',
            prop: 'title',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '服务ID',
            prop: 'serviceId',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '创建者ID',
            prop: 'createId',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '创建者',
            prop: 'createBy',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '操作IP地址',
            prop: 'remoteAddr',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '用户代理',
            prop: 'userAgent',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '请求URI',
            prop: 'requestUri',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '操作方式',
            prop: 'method',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '操作提交的数据',
            prop: 'params',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '执行时间',
            prop: 'execTime',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '异常信息',
            prop: 'exception',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '记录状态',
            prop: 'rstate',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '创建时间',
            prop: 'createTime',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        {
            label: '修改时间',
            prop: 'updateTime',
            sortable: false,
            hide: false,
            showColumn: true,
            addDisplay: true,
            editDisplay: true,
            viewDisplay: true,
        },
        ]
}
